added and applied Button style
anb-hq/CnD_Starbucks_Clone pull request #11
Opened 2023-07-19 10:51 UTC by kimsang-mok

Please review these button styles! #10

2023-07-19 11:59 UTC, SreyNann requested changes
Review had done✅

2023-07-19 11:59 UTC, SreyNann commented on src/Components/Button/Button.scss
Why hover effect doesn't apply on the 'button-light-outline'?

2023-07-19 12:01 UTC, SreyNann approved these changes

2023-07-20 01:10 UTC, kimsang-mok commented on src/Components/Button/Button.scss
This button was made for testing purposes, but I forgot to remove it right away! Thanks for mentioning it! I'll delete these lines before finishing this branch.

2023-07-20 01:13 UTC, closed without merging